### ISSUE TITLE
capcut version

### ISSUE THREAD

**Issue by yeucodonvn** [emosheeep/capcut-export#3]
I see you announced that from April 2024, CapCut drafts will be encrypted. So, if I use the 2023 version of CapCut, will it still work?

**Comment by emosheeep** [comment]
Yes it supposes to be work if the draft_content.json isn't encrypted.

**Comment by yeucodonvn** [comment]
It can export a project containing various components, subtitle, visual effects, audio, video file speed, and more.

**Comment by yeucodonvn** [comment]
I am using Windows 10 and Node.js v22, along with CapCut 3.2. The draft_content.json file is not encrypted, but it seems that pnpm is not functioning properly on Windows. Have you encountered this error before? Could you guide me on how to resolve it?
``` 

C:\Users\Admin\AppData\Local\CapCut\User Data\Projects\com.lveditor.draft\1207>ccexp "C:\Users\Admin\AppData\Local\CapCut\User Data\Projects\com.lveditor.draft\1207\draft_content.json"
file:///C:/Users/Admin/AppData/Local/pnpm/global/5/.pnpm/zx@7.2.3/node_modules/zx/build/core.js:146
            let output = new ProcessOutput(code, signal, stdout, stderr, combined, message);
                         ^

ProcessOutput [Error]: which : The term 'which' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ which ffmpeg
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (which:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

    at exportVideos (file:///C:/Users/Admin/AppData/Local/pnpm/global/5/.pnpm/capcut-export@1.0.1/node_modules/capcut-export/dist/index.js:40:31)
    exit code: 1
    at ChildProcess.<anonymous> (file:///C:/Users/Admin/AppData/Local/pnpm/global/5/.pnpm/zx@7.2.3/node_modules/zx/build/core.js:146:26)
    at ChildProcess.emit (node:events:524:28)
    at maybeClose (node:internal/child_process:1101:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17) {
  _code: 1,
  _signal: null,
  _stdout: '',
  _stderr: "which : The term 'which' is not recognized as the name of a cmdlet, function, script file, or operable program. Check \r\n" +
    'the spelling of the name, or if a path was included, verify that the path is correct and try again.\r\n' +
    'At line:1 char:1\r\n' +
    '+ which ffmpeg\r\n' +
    '+ ~~~~~\r\n' +
    '    + CategoryInfo          : ObjectNotFound: (which:String) [], CommandNotFoundException\r\n' +
    '    + FullyQualifiedErrorId : CommandNotFoundException\r\n' +
    ' \r\n',
  _combined: "which : The term 'which' is not recognized as the name of a cmdlet, function, script file, or operable program. Check \r\n" +
    'the spelling of the name, or if a path was included, verify that the path is correct and try again.\r\n' +
    'At line:1 char:1\r\n' +
    '+ which ffmpeg\r\n' +
    '+ ~~~~~\r\n' +
    '    + CategoryInfo          : ObjectNotFound: (which:String) [], CommandNotFoundException\r\n' +
    '    + FullyQualifiedErrorId : CommandNotFoundException\r\n' +
    ' \r\n'
}

Node.js v22.12.0
```

**Comment by emosheeep** [comment]
it seems a upstream problem, caused by zx

**Comment by emosheeep** [comment]
have you installed ffmpeg on your computer and add it to the env path？

**Comment by yeucodonvn** [comment]
Yes, I have added FFMPEG to the PATH
 zx version 8.2.4

**Comment by emosheeep** [comment]
You can try to exec the command in Git Terminal on Windows.

**Comment by yeucodonvn** [comment]
> You can try to exec the command in Git Terminal on Windows.

It has worked, but it only exports the video without any visual effects or sound from the project

**Comment by emosheeep** [comment]
yes it is designed for material archive not for production。

**Comment by yeucodonvn** [comment]
Too bad, I actually need to export the entire project with all its accompanying elements.

**Comment by emosheeep** [comment]
![CleanShot 2024-12-08 at 11 35 55@2x](https://github.com/user-attachments/assets/24fec43d-9d99-4162-b79b-af8f29482bd9)

**Comment by yeucodonvn** [comment]
I use the international version of CapCut and cannot find that attribute line. If possible, please display it in English. Anyway, thank you for your support!

**Comment by emosheeep** [comment]
It's the chinese version of Capcut, but it's a functionality that is in grayscale. Whether you can use it or not may depend on your luck. You can have a try yourself.

**Comment by remorses** [comment]
My CapCut projects are not encrypted, could it be an issue of the CapCut free version only? In my CapCut version all project files are plain .json

**Comment by yeucodonvn** [comment]
> My CapCut projects are not encrypted, could it be an issue of the CapCut free version only? In my CapCut version all project files are plain .json

what version are you using?

**Comment by remorses** [comment]
Latest one on Mac app store
